### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-3-sintesis-salathiel1999#2]
[sintesisG.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-salathiel1999/files/9466443/sintesisG.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 19/20

Hay errores de ortografía y texto no justificado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
